#!/bin/bash
# Use this for your user data (script from top to bottom)
# install Apache (Ubuntu version)
apt-get update -y
sudo apt-get install -y apache2
sudo systemctl start apache2
sudo systemctl enable apache2
sudo echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html


sudo waagent -deprovision+user